var taqHome;
(function(){function wa(){var a=n.getElementById("NewsEditionName"),b=n.getElementById("NewsEditionNumber"),c=n.getElementById("NewsArticleTitle"),d=n.getElementById("NewsArticleAuthor"),g=n.getElementById("NewsArticleID"),e=n.getElementById("NewsArticleType"),B=n.getElementById("NewsPaperName"),s=n.getElementById("NewsArticleSource"),v=n.getElementById("NewsArticlePubDay"),k=n.getElementById("SelfNewsArticleID");if(b||g)g&&(f.a_id=r(g.innerHTML)),c&&(c=r(c.innerHTML).replace(/<br.*?>/g," "),f.a_nt=
c),b&&(f.a_en=r(b.innerHTML)),a&&(f.a_ea=r(a.innerHTML)),e&&(f.a_tp=r(e.innerHTML)),B&&(f.a_pn=r(B.innerHTML)),s&&(f.a_src=r(s.innerHTML)),d&&(f.a_ar=r(d.innerHTML)),v&&(f.a_pd=r(v.innerHTML)),k&&(f.a_sid=r(k.innerHTML));f.title=w.title||""}function Xa(a){K||(q("user state returned."),K=!0,(C=String(a))&&"null"!=C&&"undefined"!=C?(ca("_trs_user",C,"/",null,R(w.domain)),f.uid=C):(a=R(w.domain),ca("_trs_user","","/",new Date(0),a)))}function xa(a){return null==a||void 0==a?!0:"string"!=typeof a?!1:
0==r(a).length}function r(a){return a.replace(/^\s+|\s+$/gm,"")}function m(a,b){return null==a||void 0==a?a:r(a).length>b?a.substring(0,b-3)+"...":a}function da(a){var b=n.cookie.indexOf(a+"=");if(-1==b)return null;b=b+a.length+1;a=n.cookie.indexOf(";",b);-1==a&&(a=n.cookie.length);return decodeURIComponent(n.cookie.substring(b,a))}function ya(a,b,c,d,g){null==g||void 0==g||0==S(g)?n.cookie=a+"="+encodeURIComponent(b)+"; path="+c+"; expires="+d:n.cookie=a+"="+encodeURIComponent(b)+"; path="+c+"; domain="+
g+"; expires="+d}function ca(a,b,c,d,g){a=encodeURIComponent(a)+"="+encodeURIComponent(b);c&&(a+="; path="+c);d instanceof Date&&(a+="; expires="+d.toGMTString());g&&(a+="; domain="+g);n.cookie=a}function za(a){if(xa(a)||"undefined"==a||"string"!=typeof a)return!0;if(24<a.length)return q("length="+a.length+": "+a),!0;var b=/^[^_=]{1,5}_\d+_[^_=]{8,9}$/;return/^[^_=]{8,9}_\d+_[^_=]{1,5}$/.test(a)||b.test(a)?!1:(q(a+" not valid"),!0)}function Aa(a){var b=parseInt(Math.floor(1E3*Math.random()+1)+""+
Math.floor(1E3*Math.random()+1));return String((new Date).valueOf().toString(36).concat("_").concat(a).concat("_").concat(b.toString(36)))}function q(a){if(window.console&&console.log)try{console.log(a)}catch(b){}}function Ya(){var a;try{return a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),a.GetVariable("$version")}catch(b){}try{return a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),version="WIN 6,0,21,0",a.AllowScriptAccess="always",a.GetVariable("$version")}catch(c){}try{return a=
new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3"),a.GetVariable("$version")}catch(d){}try{return new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3"),"WIN 3,0,18,0"}catch(g){}try{return new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),"WIN 2,0,0,11"}catch(e){return"-1"}}function Za(){var a="Shockwave Flash ";if(navigator.plugins&&0<navigator.plugins.length){var b=navigator.plugins["Shockwave Flash"];if(!b)return"-1";try{if(void 0!=b.version)return b.version}catch(c){}b=b.description;return-1!=
b.indexOf(a)?b.substring(a.length):b}for(var b=Ya().split(","),d="",a="WIN ",g=0,e=b.length;g<e;g++)-1!=b[g].indexOf(a)?(d+=b[g].substring(a.length),d+="."):g==e-1?d+=b[g]:(d+=b[g],d+=".");return d}function ea(){var a=!f.uid&&!K&&3E3>(new Date).getTime()-Ba;L||("true"!=Ca?(wa(),L=!0):S(w.title)?(wa(),L=!0):L=!1);var b=!L&&3E3>(new Date).getTime()-Da;if(a||b)setTimeout(ea,500);else{var a="",c;for(c in f)xa(f[c])||(""!=a&&(a+="&"),a+=c+"="+encodeURIComponent(f[c]));if(taqHome){try{fa=(new Date).getTime(),
Ea=f.mpId}catch(d){}c=new Image(1,1);c.src=taqHome+"/1.gif?"+a;D(c.src,"pv")}else q("no _taq.home!")}}function Fa(a){a=G.timing;try{if(0>=parseInt(a.loadEventEnd))setTimeout(function(){$a++;Fa(f)},50);else{var b=a.domainLookupEnd-a.domainLookupStart,c=a.connectEnd-a.connectStart,d=a.responseStart-a.requestStart,g=a.domContentLoadedEventStart-a.fetchStart,e=a.responseEnd-a.navigationStart,B=ab(),s;-1!==h.navigator.userAgent.indexOf("Chrome")&&(f.p_fp=-1,h.chrome&&window.PerformancePaintTiming&&(s=
((performance.getEntriesByType("paint")[0].startTime+performance.timeOrigin)/1E3).toFixed(3),f.p_fp=0<=s?s:-1));-1!=navigator.appName.indexOf("Microsoft Internet Explorer")&&document.all&&(s=a.msFirstPaint-a.navigationStart,f.p_fp=0<=s?s:-1);requestType=G.navigation.type;var v=a.loadEventEnd-a.navigationStart;f.p_d=0<=b?b:-1;f.p_ct=0<=c?c:-1;f.p_st=0<=d?d:-1;f.p_nt=0<=e?e:-1;f.p_tt=0<=v?v:-1;f.p_dr=0<=g?g:-1;f.p_rt=requestType;f.p_c=0;f.p_tajs=0<=B?Math.floor(B):-1;1===requestType&&(f.p_c=0);0===
a.requestStart&&(f.p_c=1);a.connectStart===a.connectEnd&&(f.p_c=1);if("getEntriesByType"in G&&G.getEntriesByType("resource")instanceof Array){var k=G.getEntriesByType("resource");f.p_rc=k.length}ea()}}catch(l){}}function ab(){var a=0;try{var b=n.getElementById("_trs_ta_js").src,c=h.performance.getEntriesByName(b);0<c.length&&(a=c[0].duration)}catch(d){}return a}function bb(a){var b=a.getAttribute("data-trs-ta-event-key");if(null==b||"undefined"==b||""==b||"null"==b){for(;(a=a.parentNode)&&1==a.nodeType;)if(b=
a.getAttribute("data-trs-ta-event-key"),null!=b&&"undefined"!=b&&""!=b&&"null"!=b)return a;return null}return a}function S(a){return"string"!=typeof a?!1:0<a.length}function y(a){return null==a||"undefined"==a||""==a||"null"==a?a:a.replace(/\t/g," ").replace(/(^\s*)|(\s*$)/g,"").replace(/[\r\n]/g," ")}function T(a){return null==a||"undefined"==a||""==a||"null"==a?a:a.replace(/(^\s*)|(\s*$)/g,"")}function k(a,b,c){null!=c&&"undefined"!=c&&""!=c&&"null"!=c&&(a+="&"+b+"="+c);return a}function M(){if("spa"==
ga){var a=m(document.URL,1024);return m(encodeURIComponent(a),1024)}return m(encodeURIComponent(N),1024)}function ha(a,b,c){var d=b.getAttribute("href"),g=d?d.match(/^#/):!1,e=g?d:b.href;e&&(e=m(T(e),255));var B=m(b.id,255),d=m(y(b.innerText),255);c&&c.elemText&&(d=m(y(c.elemText),255));d||(d=ia(b));c=m(b.type,255);var s=m(b.name,255);b=m(b.target,255);a=k(a,"mpId",Ea);a=k(a,"cs",f.cs);a=k(a,"cu",f.cu);a=k(a,"pv",f.pv);a=k(a,"e_id",B);a=k(a,"url",M());if(S(e)&&(a=k(a,"e_tu",encodeURIComponent(e)),
!g)){var v,e=T(e);0==e.indexOf("http")||0==e.indexOf("https")?(g=e.substring(0,e.indexOf("://")),e=e.substring(e.indexOf("://")+3),-1<e.indexOf("/")?v=e.substring(0,e.indexOf("/")):v=e):0==e.indexOf("//")?(g=null,e=e.substring(e.indexOf("//")+2),-1<e.indexOf("/")?v=e.substring(0,e.indexOf("/")):v=e):-1<e.indexOf(":")?(g=e.substring(0,e.indexOf(":")),v=null):(g=null,v=parseDomain2(document.URL));a=k(a,"e_td",encodeURIComponent(v));a=k(a,"e_tp",encodeURIComponent(g))}a=k(a,"e_tt",c);a=k(a,"e_tx",encodeURIComponent(d));
a=k(a,"e_en",s);return a=k(a,"e_ht",b)}function D(a,b){if(ja&&ka){switch(ka){case "0":return!1;case "1":if("pv"!=b)return!1;break;case "2":if("click"!=b)return!1;break;case "3":if("track"!=b)return!1;break;case "4":if("pv"!=b&&"click"!=b)return!1;break;case "5":if("leave"==b)return!1;break;default:return!1}a.split("/1.gif?");for(var c=a.split("/1.gif?")[1],d=ja.split(","),g,e=/^(http(s)?:)?\/\//,f,s=0;s<d.length;s++)g=e.test(d[s])?d[s]:"//"+d[s],taqHome!=g&&(f=new Image(1,1),f.src=g+"/1.gif?"+c)}}
function la(a){var b,c;b=Math.floor(a.pageX);c=Math.floor(a.pageY);var d=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;isNaN(b)&&(c=Math.max(document.documentElement.scrollTop,document.body.scrollTop),b=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),c=Math.floor(a.clientY+c),b=Math.floor(a.clientX+b));return{x:b,y:c,z:Math.floor(b-d/2)}}function cb(a){for(var b={flag:!1},c=a;c&&1==c.nodeType;c=c.parentNode)if(c.getAttribute("href")){b.anchorEle=
c;b.anchorText=function(){if("area"==c.nodeName.toLowerCase()){var a=c.parentNode,b=a.name||a.id,a=function(){for(var a=null,c=document.getElementsByTagName("img"),d=0;d<c.length;d++)if(c[d].getAttribute("usemap")=="#"+b){a=c[d];break}return a}();return ia(a)}a=m(y(Ga(c)),19);if(0<a.length)return a;a=m(y(c.title),19);if(0<a.length)return a;var e;return(a=function(){for(var a="",b=c.childNodes,d=0;d<b.length;d++)if(1==b[d].nodeType&&(e||(e=b[d]),"img"==b[d].nodeName.toLowerCase())){a=b[d];break}return a}())?
ia(a):e?e.nodeName.toLowerCase()+" "+m(y(Ga(e)),19):""}();b.flag=!0;break}return b}function ia(a){if(!a)return"";var b=a.getAttribute("alt")?T(a.getAttribute("alt")):"",c=a.getAttribute("title")?T(a.getAttribute("title")):"";a=a.getAttribute("src")?a.getAttribute("src"):"";return m(y(b?b:c?c:a),25)}function Ga(a){return a?"string"==typeof a.textContent?a.textContent:a.innerText:""}function Ha(){if(""!=H){U+="&pa=["+H+"]";H="";var a=new Image(1,1);a.src=U+"&pv="+f.pv;D(a.src,"click","click_1");U=I+
"&clicktype=1&url="+M()}}function Ia(){if(""!=E){u+="&br="+ma+"*"+V;u+="&pa=["+E+"]";u+="&pb=["+O+"]";O=E="";var a=new Image(1,1);a.src=u;D(a.src,"click","click_3");u=I+"&clicktype=3&url="+M()}}function R(a){for(var b=".com.cn .net.cn .org.cn .gov.cn .edu.cn .ac.cn .mil.cn .ah.cn .bj.cn .cq.cn .fj.cn .gd.cn .gs.cn .gz.cn .gx.cn .ha.cn .hb.cn .he.cn .hi.cn .hl.cn .hn.cn .jl.cn .js.cn .jx.cn .ln.cn .nm.cn .nx.cn .qh.cn .sc.cn .sd.cn .sh.cn .sn.cn .sx.cn .tj.cn .xj.cn .xz.cn .yn.cn .zj.cn .hk.cn .mo.cn .tw.cn .com .cn .net .cc .org .tv .edu .mil .info .mobi .biz .pro .travel .museum .int .areo .post .rec".split(" "),
c="",d=0;d<b.length;d++){var c=b[d],g=c.replace(".","\\."),g=new RegExp(g+"$");if(g.test(a)){a=a.replace(g,"");a=a.substring(a.lastIndexOf(".")+1,a.length);a+=c;break}}return a}function F(a,b,c){1<h.ta_count||(a.attachEvent?a.attachEvent("on"+b,c):a.addEventListener&&a.addEventListener(b,c,!1))}function Ja(a){a=document.documentElement&&document.documentElement.scrollHeight||document.body&&document.body.scrollHeight||0;var b=window.innerHeight||V;na=Math.max(document.documentElement.scrollTop||document.body.scrollTop,
na);W=Number((na+b)/a).toFixed(4)}function Ka(){}function La(a){return a.offsetParent?La(a.offsetParent)+a.offsetTop:a.offsetTop}function Ma(a){return a.offsetParent?Ma(a.offsetParent)+a.offsetLeft:a.offsetLeft}function db(a){var b=[],c=document.getElementById("heatmap");if(c.getContext){var d=c.getContext("2d");c.width=document.body.scrollWidth;c.height=document.body.scrollHeight}else alert("\u6d4f\u89c8\u5668\u4e0d\u652f\u6301canvas!");for(var g in a){var c=a[g].x,e=a[g].y,f=a[g].value,s=a[g].w,
k=a[g].h,l=a[g].scale,n=a[g].ele,p=new Ka;p.init(c,e,f,s,k,l,n);p.draw(d);b.push(p)}a=document.getElementById("heatmap");a=a.getContext("2d");var m=document.getElementById("tooltip"),h=[];document.getElementById("heatmap").onmousemove=function(a){var c=a.clientX;a=a.clientY;0==h.length&&(m.style.display="none");for(var d in b)if(0<c-(b[d].x-b[d].w)&&c-(b[d].x-b[d].w)<2*b[d].w&&0<a-(b[d].y-b[d].h)&&a-(b[d].y-b[d].h)<2*b[d].h){if(0<h.length){if(b[d].w>h[0].w||b[d].h>h[0].h)continue;h.pop().ele.style.border=
""}h.push(b[d]);h[0].ele.style.border="2px solid red";h[0].ele.style.boxSizing="border-box";m.style.display="block";m.style.left=c+10+"px";m.style.color="white";m.style.top=a+10+"px";var g="\u70b9\u51fb\u91cf\uff1a"+h[0].value+"<br />\u70b9\u51fb\u7387\uff1a",e;e=h[0].scale;0==e?e=0:(e=Number(100*e).toFixed(5),e+="%");m.innerHTML=g+e}else b[d].ele.style.border="",b[d]==h[0]&&h.pop()}}var f={},h=window,Na=function(a,b){var c=a.match(RegExp("(^|&|\\?|#)("+b+")=([^&#]*)(&|$|#)",""));return c?c[3]:"null"}(h.location.hash.substring(1),
"heatShow");h.TA17Obj={};var oa=h.TA17Obj,n=document,Oa=!1,X=function(){var a="",b=document.getElementsByTagName("meta");try{if(0<b.length)for(var c=0;c<b.length;c++){var d=b[c],g=d.getAttribute("charset");if(g){a=g;break}else{var e=d.getAttribute("http-equiv");if(e&&"content-type"==e.toLowerCase()){var f=d.content.split(";"),g=1<f.length?f[1].split("=")[1]:null;if(g){a=g;break}}}}}catch(k){q("fail to parse charset: "+k)}return a.toUpperCase()}(),pa=(n.characterSet?n.characterSet:n.charset).toUpperCase();
f.bc=pa;if(S(X)){f.mc=X;var Pa=/^GB/;if(!(X==pa||Pa.test(X)&&Pa.test(pa))){q("meta charset is different from browser charset, return.");return}}try{Oa=n.domain==top.document.domain}catch(eb){q("unable check top.document.domain: "+eb)}var w=Oa?top.document:n;f.domain=w.domain||"";h&&h.screen&&(f.sh=h.screen.height||0,f.sw=h.screen.width||0,f.cd=h.screen.colorDepth||0);var Qa=n.getElementById("gscrumb");Qa&&(f.gc=r(Qa.innerHTML));var Ca=!1,Da,L=!1,ga=null,J=null,ja=null,ka=null;if("undefined"!=typeof _taq){taqHome=
_taq.home;for(var t in _taq)switch(_taq[t][0]){case "_mpId":f.mpId=_taq[t][1];break;case "_setUID":_taq[t][1]&&""!=_taq[t][1]&&(f.uid=_taq[t][1])}}else{var qa=n.getElementById("_trs_ta_js");if(!qa){q("not found _trs_ta_js script element, so just return!");return}var Y=qa.src.split("?")[1].split("&");for(t=0;t<Y.length;t++)try{var P=Y[t].split("=")[0],Q=Y[t].split("=")[1];"mpid"==P?f.mpId=Q:"waitTitle"==P?Ca=Q:"siteType"==P?ga=Q:"cPrefix"==P?(J=Q,/^(http(s)?:)?\/\//.test(J)||(J="//"+J)):"srcMode"==
P&&(ka=Q)}catch(hb){q("skip a param as it is not key=value format, i="+t+", myselfSrcParamArray="+Y)}taqHome=J?J:qa.src.split("/js/")[0];ja=document.getElementById("_trs_ta_js").srcsup||document.getElementById("_trs_ta_js").getAttribute("srcsup")||void 0}h.ta_count=h.ta_count||0;if("spa"==ga)h.ta_count++;else{if(h["ta.js"])return;h["ta.js"]=!0}Da=(new Date).getTime();var C=da("_trs_user"),Ba,K=!1;if(C)f.uid=C,q("get user id from cookie");else if("undefined"!=typeof window.TA17Callbacks_getAndSendLoginUser){Ba=
(new Date).getTime();try{q("start to get user id"),window.TA17Callbacks_getAndSendLoginUser(Xa)}catch(ib){q("no valid method for getting user was provided."),K=!0}}else q("no valid method for getting user was provided."),K=!0;oa.clearLoginUser=function(){var a=R(w.domain);ca("_trs_user","","/",new Date(0),a)};var x,A;f.pv=function(a){var b=parseInt(Math.floor(1E3*Math.random()+1)+""+Math.floor(1E3*Math.random()+1));return String((a+"").concat("_").concat((new Date).valueOf().toString(36)).concat("_").concat(b.toString(36)))}(f.mpId);
0<n.cookie.length&&(x=da("_trs_ua_s_1"),A=da("_trs_uv"));if(za(x)){var fb=x;x=Aa(f.mpId);q("sessionCookie expired: "+fb+", so create new: "+x)}if(za(A)){var gb=A;A=Aa(f.mpId);q("UVCookie expired: "+gb+", so create new: "+A)}var ra=new Date;ra.setDate(ra.getDate()+730);var Ra=R(w.domain);ya("_trs_uv",A,"/",ra.toGMTString(),Ra);q("set UVCookie topLevelDomain: "+Ra+", _trs_uv="+A);var sa=new Date;sa.setMinutes(sa.getMinutes()+30);ya("_trs_ua_s_1",x,"/",sa.toGMTString());q("set sessionCookie: _trs_ua_s_1="+
x);f.cs=x||"";f.cu=A||"";f.title=w.title||"";f.url=w.URL||"";f.refer=w.referrer||"";if(1==Na){var Z=document.createElement("iframe"),ta;ta=document.referrer&&"function"==typeof document.referrer.indexOf&&0<=document.referrer.indexOf("/console/heatmap")?document.referrer.slice(0,document.referrer.indexOf("/console/heatmap")):taqHome;var ua=document.documentElement.scrollWidth,$=document.documentElement.scrollHeight,aa=0;Z.src=ta+"/agent.html#"+ua+"*"+$;document.body.appendChild(Z);Z.style.display=
"none";var Sa=function(){document.documentElement.scrollHeight!=$?(aa=0,ua=document.documentElement.scrollWidth,$=document.documentElement.scrollHeight,Z.src=ta+"/agent.html?random="+Math.random()+"#"+ua+"*"+$):3>=aa?(aa++,setTimeout(Sa,1E3)):aa=0};F(window,"resize",Sa);Na=0}var ba={listenMessage:function(a){F(window,"message",a)},postMessage:function(a){try{window.parent.postMessage(a,"*")}catch(b){q(b.message)}}},Ta=!1;ba.listenMessage(function(a){function b(){document.body.scrollHeight!=d&&(c=
document.body.scrollWidth,d=document.body.scrollHeight,ba.postMessage({type:"contentSize",value:[c,d]}))}var c="",d="";a.data&&"taHeatShow"==a.data.type&&(Ta||(Ta=!0,F(window,"resize",b)),c=document.body.scrollWidth,d=document.body.scrollHeight,ba.postMessage({type:"contentSize",value:[c,d]}))});document.onreadystatechange=function(){window.postMessage&&"complete"==document.readyState&&ba.postMessage({type:"contentSize",value:[document.body.scrollWidth,document.body.scrollHeight]})};navigator&&(f.lang=
navigator.language||navigator.browserLanguage||"",f.fl=Za(),f.je=navigator.javaEnabled()?1:0,f.ce=navigator.cookieEnabled?1:0);var G=h.performance,$a=0;G?Fa(f):ea();var fa=0,Ea=f.mpId;/msie (\d+\.\d+)/i.test(navigator.userAgent);var Ua=taqHome+"/1.gif?event=click&sr="+screen.width+"*"+screen.height+"&url="+encodeURIComponent(document.URL),p=Ua,ma=0,V=0;document.all||document.captureEvents(Event.MOUSEMOVE);var ma=document.documentElement&&document.documentElement.scrollWidth||document.body&&document.body.scrollWidth||
0,V=document.documentElement&&document.documentElement.scrollHeight||document.body&&document.body.scrollHeight||0,va=window.devicePixelRatio||1,va=Number(va).toFixed(4),N=m(document.URL,1024);0<N.indexOf("#")&&(N=N.substring(0,N.indexOf("#")));var I=taqHome+"/1.gif?event=mousedown&sr="+screen.width+"*"+screen.height+"&br="+ma+"*"+V+"&dpr="+va,U=I+"&clicktype=1&url="+M(),l=I+"&clicktype=2",u=I+"&clicktype=3&url="+M(),H="",E="",O="";oa.track=function(a){if(!a.eventKey&&0!==a.eventKey)return q("eventKey\u503c\u4e3a\uff1a"+
a.eventKey+"\u4e0d\u7b26\u5408\u547d\u540d\u89c4\u8303!"),!1;-1<a.eventKey.indexOf(".")&&(a.eventKey=a.eventKey.substring(a.eventKey.indexOf(".")+1)+"&t_t="+a.eventKey.split(".")[0]);var b,c;if(a.trackInfos&&0!=a.trackInfos.length)for(var d=0;d<a.trackInfos.length;d++)c=new Image(1,1),b=taqHome+"/1.gif?mpId="+f.mpId+"&event=jsapi&t_k="+a.eventKey+"&cu="+f.cu+"&cs="+f.cs+"&pv="+f.pv+"&url="+encodeURIComponent(f.url),a.trackInfos[d].eventItem&&(b+="&t_i="+a.trackInfos[d].eventItem),a.trackInfos[d].eventItemType&&
(b+="&t_it="+a.trackInfos[d].eventItemType),a.trackInfos[d].eventItemName&&(b+="&t_in="+a.trackInfos[d].eventItemName),a.trackInfos[d].commodity_num&&(b+="&t_num="+a.trackInfos[d].commodity_num),a.trackInfos[d].commodity_money&&(b+="&t_money="+a.trackInfos[d].commodity_money.toFixed(2)),a.trackInfos[d].target_page&&(b+="&e_tu="+a.trackInfos[d].target_page),a.trackInfos[d].customParam&&(b+="&e_cus="+JSON.stringify(a.trackInfos[d].customParam)),c.src=b,D(b,"track");else c=new Image(1,1),b=taqHome+"/1.gif?mpId="+
f.mpId+"&event=jsapi&t_k="+a.eventKey+"&cu="+f.cu+"&cs="+f.cs+"&pv="+f.pv+"&url="+f.url,c.src=b,D(b,"track")};if(h.TAQueueArr){for(t=0;t<h.TAQueueArr.length;t++)oa.track(h.TAQueueArr[t][0]);h.TAQueueArr=[]}var Va=function(){var a=function(){return{Base64:function(){_keyStr="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";this.encode=function(a){var b="",g,e,f,k,h,l,m=0;for(a=_utf8_encode(a);m<a.length;)g=a.charCodeAt(m++),e=a.charCodeAt(m++),f=a.charCodeAt(m++),k=g>>2,g=(g&3)<<
4|e>>4,h=(e&15)<<2|f>>6,l=f&63,isNaN(e)?h=l=64:isNaN(f)&&(l=64),b=b+_keyStr.charAt(k)+_keyStr.charAt(g)+_keyStr.charAt(h)+_keyStr.charAt(l);return b};this.decode=function(a){var b="",g,e,f,k,h,l=0;for(a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");l<a.length;)g=_keyStr.indexOf(a.charAt(l++)),e=_keyStr.indexOf(a.charAt(l++)),k=_keyStr.indexOf(a.charAt(l++)),h=_keyStr.indexOf(a.charAt(l++)),g=g<<2|e>>4,e=(e&15)<<4|k>>2,f=(k&3)<<6|h,b+=String.fromCharCode(g),64!=k&&(b+=String.fromCharCode(e)),64!=h&&(b+=String.fromCharCode(f));
return b=_utf8_decode(b)};_utf8_encode=function(a){a=a.replace(/\r\n/g,"\n");for(var b="",g=0;g<a.length;g++){var e=a.charCodeAt(g);128>e?b+=String.fromCharCode(e):(127<e&&2048>e?b+=String.fromCharCode(e>>6|192):(b+=String.fromCharCode(e>>12|224),b+=String.fromCharCode(e>>6&63|128)),b+=String.fromCharCode(e&63|128))}return b};_utf8_decode=function(a){for(var b="",g=0,e=c1=c2=0;g<a.length;)e=a.charCodeAt(g),128>e?(b+=String.fromCharCode(e),g++):191<e&&224>e?(c2=a.charCodeAt(g+1),b+=String.fromCharCode((e&
31)<<6|c2&63),g+=2):(c2=a.charCodeAt(g+1),c3=a.charCodeAt(g+2),b+=String.fromCharCode((e&15)<<12|(c2&63)<<6|c3&63),g+=3);return b}},readXPath:function(a){if(""!==a.id)return"//*[@id='"+a.id+"']";for(var b=0,g=a.parentNode,e=a.parentNode.childNodes,f=0,k=e.length;f<k;f++){var h=e[f];if(h==a)return g==document.body?a.tagName.toLowerCase()+(1==b+1?"":"["+(b+1)+"]"):arguments.callee(a.parentNode)+"/"+a.tagName.toLowerCase()+(1==b+1?"":"["+(b+1)+"]");1==h.nodeType&&h.tagName==a.tagName&&b++}},indexOf:function(a,
b){if(null!=Array.prototype.indexOf)return a.indexOf(b);for(var g=0;g<a.length;g++)if(a[g]===b)return g;return-1}}}(),b=["TEXTAREA","HTML","BODY"];return{tools:a,collectable:function(c){if(c==document||!c)return!1;c=c.tagName.toUpperCase();return-1<a.indexOf(b,c)?!1:!0}}}(),Wa=Va.tools;F(document,"mouseup",function(a){if(document!=(a.target||a.srcElement)){var b=bb(a.target||a.srcElement);if(null!=b){var c=b.tagName.toLowerCase();if("a"==c||"input"==c||"button"==c){var d=m(b.getAttribute("data-trs-ta-event-key"),
255),g=m(b.getAttribute("data-trs-ta-event-type"),255),e=m(y(b.getAttribute("data-trs-ta-event-itemtype")),255),f=m(y(b.getAttribute("data-trs-ta-event-item")),255),h=m(y(b.getAttribute("data-trs-ta-event-itemname")),255),n,t,r;r=la(a);n=r.x;t=r.y;r=r.z;var w=a.type;p=ha(p,b);p=k(p,"t_k",encodeURIComponent(d));p=k(p,"t_t",encodeURIComponent(g));p=k(p,"t_it",encodeURIComponent(e));p=k(p,"t_i",encodeURIComponent(f));p=k(p,"t_in",encodeURIComponent(h));p=k(p,"x",n);p=k(p,"y",t);p=k(p,"x2",r);p=k(p,"e_tn",
c);p=k(p,"e_et",w);(new Image(1,1)).src=p;p=Ua}}b=a.target||a.srcElement;if(null!=b&&(e=m(b.tagName.toLowerCase(),255),g=la(a),c=g.x,d=g.y,g=g.z,f=Va.collectable(b),h=cb(b),n="a"==e||"input"==e||"button"==e,"a"!=e&&"input"!=e&&"button"!=e&&(H=""==H?"{"+c+","+d+","+g+"}":H+(";{"+c+","+d+","+g+"}"),Ha()),n||f)){h.flag?(l=ha(l,h.anchorEle,{elemText:h.anchorText}),e=m(h.anchorEle.tagName.toLowerCase(),255),l=k(l,"e_tn",e),l=k(l,"e_iac","1")):(l=ha(l,b),l=k(l,"e_tn",e),l=k(l,"e_iac","0"));e=m(a.type,255);
f="";h=0;try{var z=Wa.readXPath(b),u=new Wa.Base64,f=encodeURIComponent(u.encode(z));0!=fa&&(h=Math.floor(((new Date).getTime()-fa)/1E3))}catch(x){q("someting wrong for getting element xPath"),q(x)}l=k(l,"e_et",e);l=k(l,"e_nd",f);l=k(l,"e_etd",h);l=k(l,"x",c);l=k(l,"y",d);l=k(l,"x2",g);if(isNaN(c))try{l=k(l,"p_err",JSON.stringify({isPage:a.pageX,isClient:a.clientX,isScroll:document.documentElement.scrollTop,isBodyScroll:document.body.scrollTop}))}catch(A){}z=new Image(1,1);z.src=l;D(z.src,"click",
"click_2");l=I+"&clicktype=2"}u=la(a);a=u.x;z=u.y;u=u.z;""==E?(E="{x:"+a+",y:"+z+"}",O="{z:"+u+",y:"+z+"}"):(E+=",{x:"+a+",y:"+z+"}",O+=",{z:"+u+",y:"+z+"}");Ia()}});F(window,"unload",function(){W||Ja();var a=1>W?W:1,b=new Image(1,1),a=taqHome+"/1.gif?mpId="+f.mpId+"&event=viewInfo&cu="+f.cu+"&cs="+f.cs+"&pv="+f.pv+"&vp="+a+"&url="+encodeURIComponent(f.url);b.src=a;D(a,"leave");Ha();Ia()});F(window,"scroll",Ja);var na=0,W;Ka.prototype={init:function(a,b,c,d,f,e,h){this.x=a;this.y=b;this.value=c;this.w=
d;this.h=f;this.scale=e;this.ele=h},draw:function(a){a.beginPath();a.ellipse(this.x,this.y,this.w,this.h,0,0,2*Math.PI);a.closePath();var b=this.w>this.h?this.w:this.h;0==b&&(b=1);a.save();a.scale(this.w/b,this.h/b);var c=this.x/(0==this.w/b?1:this.w/b),d=this.y/(0==this.h/b?1:this.h/b),b=a.createRadialGradient(c,d,0,c,d,b);.001>this.scale?(b.addColorStop(0,"rgba(0,255,0,0.5)"),b.addColorStop(.5,"rgba(0,0,255,0.3)"),b.addColorStop(1,"rgba(148,0,211,0)")):.008>this.scale?(b.addColorStop(0,"rgba(0,255,255,0.5)"),
b.addColorStop(.5,"rgba(0,255,0,0.3)"),b.addColorStop(1,"rgba(0,0,255,0)")):(b.addColorStop(0,"rgba(255,0,0,0.5)"),b.addColorStop(.5,"rgba(255,255,0,0.3)"),b.addColorStop(1,"rgba(0,255,0,0)"));a.fillStyle=b;a.globalAlpha=Math.max(Math.min(2E3*this.scale,1),0);a.fill();a.restore()}};F(window,"message",function(a){if(a.data&&"dealXpath"==a.data.type){var b=document.createElement("canvas");b.setAttribute("id","heatmap");b.style.position="fixed";b.style.zIndex=999;b.style.display="block";b.style.top=
0;b.style.left=0;document.body.appendChild(b);b=document.createElement("div");b.setAttribute("id","tooltip");b.style.backgroundColor="black";b.style.width="150px";b.style.height="40px";b.style.padding="10px";b.style.position="fixed";b.style.display="none";b.style.top=0;b.style.left=0;b.style.zIndex=1E3;document.body.appendChild(b);a=a.data.data;for(var b=[],c=0;c<a.length;c++){""==a[c].xpath?a[c].xpath="html/body":0!=a[c].xpath.indexOf("/")&&(a[c].xpath="/html/body/"+a[c].xpath);var d=document.evaluate(a[c].xpath,
document).iterateNext();if(d&&(0==d.childNodes.length||0!=d.childNodes.length&&0==d.childNodes[0].childNodes.length)){var f=d.offsetWidth/2+Ma(d),e=d.offsetHeight/2+La(d);b.push({x:f,y:e,value:a[c].click,w:d.clientWidth/2,h:d.clientHeight/2,scale:a[c].click/a[c].sumClick,ele:d})}}db(b)}},!1)})();
